/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.jwolff52.cyoa.gui;

/**
 *
 * @author James
 */
public class AttributesGUI extends javax.swing.JFrame {

    /**
     * Creates new form AttributesGUI
     */
    public AttributesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        healthLabel = new javax.swing.JLabel();
        strengthLabel = new javax.swing.JLabel();
        dexterityLabel = new javax.swing.JLabel();
        bladeLabel = new javax.swing.JLabel();
        archeryLabel = new javax.swing.JLabel();
        pointsLeftLabel = new javax.swing.JLabel();
        healthDecreaseButton = new javax.swing.JButton();
        strengthDecreaseButton = new javax.swing.JButton();
        dexterityDecreaseButton = new javax.swing.JButton();
        bladeDecreaseButton = new javax.swing.JButton();
        archeryDecreaseButton = new javax.swing.JButton();
        pointsLeftValueLabel = new javax.swing.JLabel();
        healthValueLabel = new javax.swing.JLabel();
        strengthValueLabel = new javax.swing.JLabel();
        dexterityValueLabel = new javax.swing.JLabel();
        bladeValueLabel = new javax.swing.JLabel();
        archeryValueLabel = new javax.swing.JLabel();
        healthIncreaseButton = new javax.swing.JButton();
        strengthIncreaseButton = new javax.swing.JButton();
        dexterityIncreaseButton = new javax.swing.JButton();
        bladeIncreaseButton = new javax.swing.JButton();
        archeryIncreaseButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Level Up");

        healthLabel.setText("Health");

        strengthLabel.setText("Strength");

        dexterityLabel.setText("Dexterity");

        bladeLabel.setText("Blade");

        archeryLabel.setText("Archery");

        pointsLeftLabel.setText("Attribute Points Left:");

        healthDecreaseButton.setText("<");
        healthDecreaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                healthDecreaseButtonMouseReleased(evt);
            }
        });

        strengthDecreaseButton.setText("<");
        strengthDecreaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                strengthDecreaseButtonMouseReleased(evt);
            }
        });

        dexterityDecreaseButton.setText("<");
        dexterityDecreaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dexterityDecreaseButtonMouseReleased(evt);
            }
        });

        bladeDecreaseButton.setText("<");
        bladeDecreaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bladeDecreaseButtonMouseReleased(evt);
            }
        });

        archeryDecreaseButton.setText("<");
        archeryDecreaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                archeryDecreaseButtonMouseReleased(evt);
            }
        });

        pointsLeftValueLabel.setText(MainGUI.cyoa.getAdventurer().getSkillPoints()+MainGUI.cyoa.getAdventurer().getTotalInSkillBuffer()+"");

        healthValueLabel.setText(MainGUI.cyoa.getAdventurer().getMaxHealth()+MainGUI.cyoa.getAdventurer().getSkillBuffer(0)+"");

        strengthValueLabel.setText(MainGUI.cyoa.getAdventurer().getStrength()+MainGUI.cyoa.getAdventurer().getSkillBuffer(1)+"");

        dexterityValueLabel.setText(MainGUI.cyoa.getAdventurer().getDexterity()+MainGUI.cyoa.getAdventurer().getSkillBuffer(2)+"");

        bladeValueLabel.setText(MainGUI.cyoa.getAdventurer().getBlade()+MainGUI.cyoa.getAdventurer().getSkillBuffer(3)+"");

        archeryValueLabel.setText(MainGUI.cyoa.getAdventurer().getArchery()+MainGUI.cyoa.getAdventurer().getSkillBuffer(4)+"");

        healthIncreaseButton.setText(">");

        strengthIncreaseButton.setText(">");

        dexterityIncreaseButton.setText(">");

        bladeIncreaseButton.setText(">");

        archeryIncreaseButton.setText(">");

        submitButton.setText("Submit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dexterityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bladeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(archeryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(strengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(healthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(healthDecreaseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(healthValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(healthIncreaseButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(strengthDecreaseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(strengthValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(strengthIncreaseButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dexterityDecreaseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dexterityValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dexterityIncreaseButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bladeDecreaseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bladeValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bladeIncreaseButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(archeryDecreaseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(archeryValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(archeryIncreaseButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pointsLeftLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pointsLeftValueLabel))
                    .addComponent(submitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsLeftLabel)
                    .addComponent(pointsLeftValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(healthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(healthDecreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(healthValueLabel)
                        .addComponent(healthIncreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(strengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strengthDecreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(strengthValueLabel)
                        .addComponent(strengthIncreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dexterityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dexterityDecreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dexterityValueLabel)
                        .addComponent(dexterityIncreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bladeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bladeDecreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bladeValueLabel)
                        .addComponent(bladeIncreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archeryLabel)
                    .addComponent(archeryDecreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archeryValueLabel)
                    .addComponent(archeryIncreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void healthDecreaseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthDecreaseButtonMouseReleased
        if(MainGUI.cyoa.getAdventurer().getSkillBuffer(0)>1){
            MainGUI.cyoa.getAdventurer().setSkillBuffer(0, MainGUI.cyoa.getAdventurer().getSkillBuffer(0)-1);
            healthValueLabel.setText(Integer.valueOf(healthValueLabel.getText()).intValue()-1+"");
            pointsLeftValueLabel.setText(Integer.valueOf(pointsLeftValueLabel.getText()).intValue()+1+"");
        }else{
            healthDecreaseButton.setEnabled(false);
        }
    }//GEN-LAST:event_healthDecreaseButtonMouseReleased

    private void strengthDecreaseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strengthDecreaseButtonMouseReleased
        if(MainGUI.cyoa.getAdventurer().getSkillBuffer(1)>0){
            MainGUI.cyoa.getAdventurer().setSkillBuffer(1, MainGUI.cyoa.getAdventurer().getSkillBuffer(1)-1);
            strengthValueLabel.setText(Integer.valueOf(strengthValueLabel.getText()).intValue()-1+"");
            pointsLeftValueLabel.setText(Integer.valueOf(pointsLeftValueLabel.getText()).intValue()+1+"");
        }else{
            strengthDecreaseButton.setEnabled(false);
        }
    }//GEN-LAST:event_strengthDecreaseButtonMouseReleased

    private void dexterityDecreaseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dexterityDecreaseButtonMouseReleased
        if(MainGUI.cyoa.getAdventurer().getSkillBuffer(2)>0){
            MainGUI.cyoa.getAdventurer().setSkillBuffer(2, MainGUI.cyoa.getAdventurer().getSkillBuffer(2)-1);
            dexterityValueLabel.setText(Integer.valueOf(dexterityValueLabel.getText()).intValue()-1+"");
            pointsLeftValueLabel.setText(Integer.valueOf(pointsLeftValueLabel.getText()).intValue()+1+"");
        }else{
            dexterityDecreaseButton.setEnabled(false);
        }
    }//GEN-LAST:event_dexterityDecreaseButtonMouseReleased

    private void bladeDecreaseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bladeDecreaseButtonMouseReleased
        if(MainGUI.cyoa.getAdventurer().getSkillBuffer(3)>0){
            MainGUI.cyoa.getAdventurer().setSkillBuffer(3, MainGUI.cyoa.getAdventurer().getSkillBuffer(3)-1);
            bladeValueLabel.setText(Integer.valueOf(bladeValueLabel.getText()).intValue()-1+"");
            pointsLeftValueLabel.setText(Integer.valueOf(pointsLeftValueLabel.getText()).intValue()+1+"");
        }else{
            bladeDecreaseButton.setEnabled(false);
        }
    }//GEN-LAST:event_bladeDecreaseButtonMouseReleased

    private void archeryDecreaseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archeryDecreaseButtonMouseReleased
        if(MainGUI.cyoa.getAdventurer().getSkillBuffer(4)>0){
            MainGUI.cyoa.getAdventurer().setSkillBuffer(4, MainGUI.cyoa.getAdventurer().getSkillBuffer(4)-1);
            archeryValueLabel.setText(Integer.valueOf(archeryValueLabel.getText()).intValue()-1+"");
            pointsLeftValueLabel.setText(Integer.valueOf(pointsLeftValueLabel.getText()).intValue()+1+"");
        }else{
            archeryDecreaseButton.setEnabled(false);
        }
    }//GEN-LAST:event_archeryDecreaseButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttributesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttributesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttributesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttributesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttributesGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archeryDecreaseButton;
    private javax.swing.JButton archeryIncreaseButton;
    private javax.swing.JLabel archeryLabel;
    private javax.swing.JLabel archeryValueLabel;
    private javax.swing.JButton bladeDecreaseButton;
    private javax.swing.JButton bladeIncreaseButton;
    private javax.swing.JLabel bladeLabel;
    private javax.swing.JLabel bladeValueLabel;
    private javax.swing.JButton dexterityDecreaseButton;
    private javax.swing.JButton dexterityIncreaseButton;
    private javax.swing.JLabel dexterityLabel;
    private javax.swing.JLabel dexterityValueLabel;
    private javax.swing.JButton healthDecreaseButton;
    private javax.swing.JButton healthIncreaseButton;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JLabel healthValueLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pointsLeftLabel;
    private javax.swing.JLabel pointsLeftValueLabel;
    private javax.swing.JButton strengthDecreaseButton;
    private javax.swing.JButton strengthIncreaseButton;
    private javax.swing.JLabel strengthLabel;
    private javax.swing.JLabel strengthValueLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
