/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cyoa.gui;

import cyoa.adventure.Adventurer;
import cyoa.ChooseYourOwnAdventure;
import java.io.FileNotFoundException;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        initGame();
        
    }
    
    private static void updateStats(Adventurer adv){
        
    }
    private void initGame(){
        Thread t=new Thread(new Runnable(){
            @Override
            public void run(){
                try {
                     cyoa=new ChooseYourOwnAdventure();
                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                 }
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        typeBox = new javax.swing.JTextField();
        textareaScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        characterInfoArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newGameMenuItem = new javax.swing.JMenuItem();
        startGameMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose Your Own Adventure");

        mainPanel.setBackground(new java.awt.Color(153, 0, 0));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setName("CYOA"); // NOI18N

        typeBox.setBackground(new java.awt.Color(0, 0, 0));
        typeBox.setForeground(new java.awt.Color(102, 255, 0));
        typeBox.setText("Type Here...");
        typeBox.setToolTipText("Response Box");
        typeBox.setFocusable(false);
        typeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                typeBoxMouseEntered(evt);
            }
        });
        typeBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                typeBoxFocusGained(evt);
            }
        });

        textareaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 204, 0));
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Dialog Window");
        jTextArea1.setFocusable(false);
        textareaScrollPane.setViewportView(jTextArea1);

        characterInfoArea.setBackground(new java.awt.Color(0, 0, 0));
        characterInfoArea.setColumns(20);
        characterInfoArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        characterInfoArea.setForeground(new java.awt.Color(102, 255, 0));
        characterInfoArea.setRows(5);
        characterInfoArea.setText("Health:\nGold:\nSkills:\n    Health: \n    Strength:\n    Dexterity:\n    Blade:\n    Archery:\nInventory:\n    Blade:\n    Bow:");
        characterInfoArea.setToolTipText("Character Attributes");
        characterInfoArea.setFocusable(false);
        jScrollPane1.setViewportView(characterInfoArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(typeBox)
                    .addComponent(textareaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(textareaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        fileMenu.setText("File");

        newGameMenuItem.setText("New Game");
        newGameMenuItem.setToolTipText("Creates a New Game");
        newGameMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newGameMenuItemMouseReleased(evt);
            }
        });
        fileMenu.add(newGameMenuItem);

        startGameMenuItem.setText("Start Game");
        startGameMenuItem.setToolTipText("Lets you select a Save File");
        fileMenu.add(startGameMenuItem);

        exitMenuItem.setText("Quit");
        exitMenuItem.setToolTipText("Save and Quit");
        exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMenuItemMouseReleased(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        helpMenuItem.setText("Help File");
        helpMenuItem.setToolTipText("Show Help");
        helpMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                helpMenuItemMouseReleased(evt);
            }
        });
        helpMenu.add(helpMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeBoxMouseEntered
        typeBox.setFocusable(true);
    }//GEN-LAST:event_typeBoxMouseEntered

    private void exitMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuItemMouseReleased
        Adventurer adv=cyoa.getAdventurer();
        if(adv!=null){
            System.out.println(adv.getName());
            System.out.println(adv);
            //Implement save game
        }else{
            int x=JOptionPane.showOptionDialog(null,"Are You Sure to Close this Application?","Exit Confirmation", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(x==JOptionPane.YES_OPTION){
                System.exit(1);
            }
        }
    }//GEN-LAST:event_exitMenuItemMouseReleased

    private void newGameMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameMenuItemMouseReleased
        new Thread(new Runnable(){
            @Override
            public void run(){
                NewGameGUI newGame=new NewGameGUI();
                newGame.setVisible(true);
            }
        }).start();
    }//GEN-LAST:event_newGameMenuItemMouseReleased

    private void typeBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typeBoxFocusGained
        typeBox.setText("");
    }//GEN-LAST:event_typeBoxFocusGained

    @SuppressWarnings("empty-statement")
    private void helpMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuItemMouseReleased
        final HelpGUI h=new HelpGUI();
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run(){
                h.setVisible(true);
            }
        });
    }//GEN-LAST:event_helpMenuItemMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    public static ChooseYourOwnAdventure cyoa;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea characterInfoArea;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JMenuItem startGameMenuItem;
    private javax.swing.JScrollPane textareaScrollPane;
    private javax.swing.JTextField typeBox;
    // End of variables declaration//GEN-END:variables
}
